---
- name: 'update and upgrade packages.'
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: remove unused dependancies
  become: true
  apt:
    autoremove: yes

- name: install dependancies
  become: true
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes

- name: create backend directory on EC2
  file:
    path: /home/ubuntu/backend
    state: directory 

- name: copy files to backend
  copy: 
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend/artifact.tar.gz


- name: unzip backend directory
  shell: |
    cd /home/ubuntu/backend
    tar xvzf artifact.tar.gz -C .
    ls -la

- name: start app
  become: true
  shell: |
    pm2 delete all
    pm2 start npm -- start
    pm2 list